task3 completed
StillSomehowSane/talking-rest pull request #2
Opened 2022-02-08 13:06 UTC by asintdivya123

2022-02-08 13:43 UTC, StillSomehowSane requested changes

2022-02-08 13:43 UTC, StillSomehowSane commented on assignment3/src/main/java/com/asint/assignment3/model/Product.java
> +	@Column(name="name")
try removing the @Column or change the names to caps

2022-02-08 13:43 UTC, StillSomehowSane commented on assignment3/src/main/java/com/asint/assignment3/model/Sales.java
> +public class Sales {
Rename to Sale

2022-02-08 13:43 UTC, StillSomehowSane commented on assignment3/src/main/java/com/asint/assignment3/model/Sales.java
> +	private int product_id;
Must follow snake case so productId

2022-02-08 13:43 UTC, StillSomehowSane commented on assignment3/src/main/java/com/asint/assignment3/repository/ProductRepo.java
> +public interface ProductRepo extends JpaRepository<Product, Serializable> {
Replace Serializable

2022-02-08 13:43 UTC, StillSomehowSane commented on assignment3/src/main/java/com/asint/assignment3/service/ProductService.java
> +			Optional<Product> dbProduct = productRepo.findById(o[0]);
Remove selects from loop

2022-02-08 13:43 UTC, StillSomehowSane commented on assignment3/src/main/java/com/asint/assignment3/repository/SalesRepo.java
> +	@Query(value = "select product_id, sum(quantity) as quantity from sales group by product_id order by sum(quantity) desc", nativeQuery = true)
Try removing native query

2022-02-09 14:50 UTC, asintdivya123 commented
requested changes pushed @StillSomehowSane

2022-02-09 14:52 UTC, StillSomehowSane approved these changes
Awesomeness

2022-02-09 14:52 UTC, StillSomehowSane commented on assignment3/src/main/java/com/asint/assignment3/repository/SaleRepo.java
> +	@Query("select s.productId, sum(s.quantity)*p.price, p.name from Sale s join Product p on s.productId = p.id group by s.productId order by sum(s.quantity) desc")
I am glad that you figured out the error without native query

2022-02-09 14:52 UTC, StillSomehowSane commented on assignment3/src/main/java/com/asint/assignment3/service/ProductService.java
> +		for(Object[] o : data ) {
Good Job!

2022-02-09 14:52 UTC, merged

2022-02-09 14:59 UTC, asintdivya123 commented
Thanq

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: StillSomehowSane ***@***.***>
Sent: Wednesday, February 9, 2022 8:23:07 PM
To: StillSomehowSane/talking-rest ***@***.***>
Cc: Divya Khatri ***@***.***>; Author ***@***.***>
Subject: Re: [StillSomehowSane/talking-rest] task3 completed (PR #2)


Merged #2<https://github.com/StillSomehowSane/talking-rest/pull/2> into main.

—
Reply to this email directly, view it on GitHub<https://github.com/StillSomehowSane/talking-rest/pull/2#event-6034971612>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AXOALAE4GVBPKYQ3QCUJRYDU2J5VHANCNFSM5N2M73YA>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-02-09 15:01 UTC, asintdivya123 commented
Yes it took time but thankfully got it

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Divya Khatri ***@***.***>
Sent: Wednesday, February 9, 2022 8:28:56 PM
To: StillSomehowSane/talking-rest ***@***.***>; StillSomehowSane/talking-rest ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [StillSomehowSane/talking-rest] task3 completed (PR #2)

Thanq

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: StillSomehowSane ***@***.***>
Sent: Wednesday, February 9, 2022 8:23:07 PM
To: StillSomehowSane/talking-rest ***@***.***>
Cc: Divya Khatri ***@***.***>; Author ***@***.***>
Subject: Re: [StillSomehowSane/talking-rest] task3 completed (PR #2)


Merged #2<https://github.com/StillSomehowSane/talking-rest/pull/2> into main.

—
Reply to this email directly, view it on GitHub<https://github.com/StillSomehowSane/talking-rest/pull/2#event-6034971612>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AXOALAE4GVBPKYQ3QCUJRYDU2J5VHANCNFSM5N2M73YA>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you authored the thread.Message ID: ***@***.***>