Task4 - Sub task 1 and 2 completed
StillSomehowSane/talking-rest pull request #3
Opened 2022-02-11 12:22 UTC by asintdivya123

2022-02-11 13:41 UTC, StillSomehowSane requested changes

2022-02-11 13:41 UTC, StillSomehowSane commented on assignment4/src/main/java/com/asint/task4/cache/Page.java
> +		// TODO: Implement
Remove

2022-02-11 13:41 UTC, StillSomehowSane commented on assignment4/src/main/java/com/asint/task4/controller/CacheController.java
> +		// TODO: Implement
Remove

2022-02-11 13:41 UTC, StillSomehowSane commented on assignment4/src/main/java/com/asint/task4/controller/CacheController.java
> +	@GetMapping("/scache/api/refresh")
add v1

2022-02-14 06:35 UTC, asintdivya123 commented
requested changes are made

2022-02-14 06:41 UTC, StillSomehowSane approved these changes
Looks good

2022-02-14 06:41 UTC, merged

2022-02-14 16:52 UTC, asintdivya123 commented
Okay 👍

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: StillSomehowSane ***@***.***>
Sent: Monday, February 14, 2022 12:11:49 PM
To: StillSomehowSane/talking-rest ***@***.***>
Cc: Divya Khatri ***@***.***>; Author ***@***.***>
Subject: Re: [StillSomehowSane/talking-rest] Task4 - Sub task 1 and 2 completed (PR #3)


Merged #3<https://github.com/StillSomehowSane/talking-rest/pull/3> into main.

—
Reply to this email directly, view it on GitHub<https://github.com/StillSomehowSane/talking-rest/pull/3#event-6064409572>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AXOALAAMZTAOAZY2XZANDH3U3CP23ANCNFSM5OEDWNKA>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you authored the thread.Message ID: ***@***.***>